services:    
  postgre_sql:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: RemTech_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5050:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  
  postgresql_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:    