// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemTech.Infrastructure.PostgreSql;

#nullable disable

namespace RemTech.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250406161112_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemTech.Domain.ParserContext.Entities.ParserProfiles.ParserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParserId")
                        .HasColumnType("uuid")
                        .HasColumnName("parser_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "RemTech.Domain.ParserContext.Entities.ParserProfiles.ParserProfile.Schedule#ParserProfileSchedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("NextRunUnixSeconds")
                                .HasColumnType("bigint")
                                .HasColumnName("next_run_unix_seconds");

                            b1.Property<long>("RepeatEveryUnixSeconds")
                                .HasColumnType("bigint")
                                .HasColumnName("repeat_every_seconds");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsDescending();

                    b.HasIndex("ParserId");

                    b.ToTable("parser_profiles", (string)null);
                });

            modelBuilder.Entity("RemTech.Domain.ParserContext.Parser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .IsDescending();

                    b.ToTable("parsers", (string)null);
                });

            modelBuilder.Entity("RemTech.Domain.ParserContext.Entities.ParserProfiles.ParserProfile", b =>
                {
                    b.HasOne("RemTech.Domain.ParserContext.Parser", "Parser")
                        .WithMany("Profiles")
                        .HasForeignKey("ParserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RemTech.Domain.ParserContext.Entities.ParserProfiles.ValueObjects.ParserProfileLinksCollection", "Links", b1 =>
                        {
                            b1.Property<Guid>("ParserProfileId")
                                .HasColumnType("uuid");

                            b1.HasKey("ParserProfileId");

                            b1.ToTable("parser_profiles");

                            b1.ToJson("Links");

                            b1.WithOwner()
                                .HasForeignKey("ParserProfileId");

                            b1.OwnsMany("RemTech.Domain.ParserContext.Entities.ParserProfiles.ValueObjects.ParserProfileLink", "Links", b2 =>
                                {
                                    b2.Property<Guid>("ParserProfileLinksCollectionParserProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Link")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("ParserProfileLinksCollectionParserProfileId", "__synthesizedOrdinal");

                                    b2.ToTable("parser_profiles");

                                    b2.WithOwner()
                                        .HasForeignKey("ParserProfileLinksCollectionParserProfileId");
                                });

                            b1.Navigation("Links");
                        });

                    b.Navigation("Links")
                        .IsRequired();

                    b.Navigation("Parser");
                });

            modelBuilder.Entity("RemTech.Domain.ParserContext.Parser", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
